Add check for init function

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -270,8 +270,13 @@ run() {
           ;;
       esac
     done
+    if [ "${type}" == "" ]; then
+      echo "Error: Type not given"
+      help init
+      exit 1
+    fi
     if [ ! -e "${APP_SELF_PATH}"/templates/"${type}" ]; then
-      echo "Type '$type' not found."
+      echo "Error: Type '$type' not found."
       exit 1
     fi
     if [ ! -e "${APP_PROJECT_PATH}/docker-compose.yml" ] && [ ! -e "${APP_PROJECT_PATH}/docker-compose.yaml" ] || [ "$force" == "1" ]; then
